### ISSUE TITLE
MCSim does no create .exe file

### ISSUE THREAD

**Issue by MSmodeler** [nanhung/MCSim_under_R#4]
I am using GNU McSim under R for a while now and evrything worked fine. However I just wanted to start another simulation with a new created model, but I am not able to create the .exe file. When I started to put my model in makemcsim the following error occurs: 

> makemcsim(model)
* The 'ZF_model_extended_v3.model.R' has been moved to modeling folder.

________________________________________

Mod v6.1.0 - Model Generator for MCSim

MCSim and associated software comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions; see the GNU General Public License.

* Created model file 'ZF_model_extended_v3.model.R.c'.

cc1.exe: fatal error: ./MCSim/sim/*.c: Invalid argument
compilation terminated.

I never met this issue before. I just changed my PC could this be the reason for this error? I have also downloaded all repositories necessary for running MCSim under R. I would appreciate your help. 

Kind regards.

**Comment by MSmodeler** [comment]
Just got fixed it on my own. The problem was the R-Version I was working with. MCSim under R only works with R Version 4.0.3 or lower (including the R-tools). The newer versions (4.2 and 4.3) gave these error message above.

**Comment by nanhung** [comment]
Thanks for the report! The issue occurs because the GCC compiler in Rtools version over 4.0 doesn't support the code in this package. The problem had been solved. Now, you can use the latest version of R and Rtools with this package.
